server:
  port: 23106

spring:
  application:
    name: integration
    index: 0

  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: 
    testWhileIdle: true
    validationQuery: SELECT 1

  jpa:
    show-sql: false
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        query.substitutions: true 1, false 0
        default_batch_fetch_size: 50
        jdbc.batch_size: 50
        order_inserts: true
        max_fetch_depth: 2
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
        connection.zeroDateTimeBehavior: convertToNull

  cloud:
    stream:
      instanceCount: 1
      instanceIndex: 0
      kafka:
        binder:
          brokers: 192.168.239.129:9092,192.168.239.129:9093,192.168.239.129:9094
          zkNodes: 192.168.239.129:2181
          offsetUpdateTimeWindow: 10000
          #offsetUpdateCount: 0
          requiredAcks: 1
          minPartitionCount: 1
          replicationFactor: 1

        bindings:
          input:
            consumer:
              autoCommitOffset: true
              startOffset: earliest
              headerMode: raw
          output:
            producer:
              bufferSize: 16384
              sync: true
              batchTimeout: 0

      bindings:
        input:
          # destination: testq1
          group: integration
          consumer:
            concurrency: 1
            partitioned: false
            headerMode: raw
        output:
          # destination: testq2
          group: integration
          producer:
            # partitionKeyExpression: null
            # partitionKeyExtractorClass: null
            # partitionSelectorExpression: null
            # partitionSelectorClass: null
            partitionCount: 1
            headerMode: raw

# Discovery Server Access
eureka:
  instance:
    preferIpAddress: true

  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/






